project:
  type: website

website:
  site-url: https://franciscorequena.com
  google-analytics: "UA-111824788-1"
  twitter-card: true
  title: "Francisco Requena"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/frequena
      - icon: twitter
        href: https://twitter.com/datarequena
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

